### ISSUE TITLE
Workflow of Discovery module is incorrect. 

### ISSUE THREAD

**Issue by hridaydutta123** [archie94/PSync#1]
Use UDP Broadcast packets assuming there is already wifi connection established between the devices. Connection establishment is managed by [DisarmConnect App](https://github.com/hridaydutta123/DisarmConnect)

**Comment by ghoshbishakh** [comment]
@archie94 As i had mentioned you need to use broadcast packets. So what you need to do is create two threads. one for broadcasting udp packets in the broadcast ip (192.168.43.255) and another thread for listening them and listing the peers

**Comment by archie94** [comment]
Thanks ! I checked and there is a bug in connection establishment between devices. Will use UDP broadcast packets

**Comment by ghoshbishakh** [comment]
assume two devices are already connected over wifi. Now the goal is to autometically detect the presence of the devices on the same network. Thats why UDP broadcasts are required.

Example:

PhoneA and PhoneB are connected to the same wifi

So target is:
in phoneA
print: ip address of PhoneB

and 
in PhoneA
print: ip address of PhoneA

**Comment by archie94** [comment]
Having problem in receiving the broadcast packet in client side. Definitely the problem lies in joining the socket to the broadcast group. Need a little help.

**Comment by ghoshbishakh** [comment]
Let me know when you are free. Will meet in department

**Comment by ghoshbishakh** [comment]
@archie94 close this issue.

**Comment by ghoshbishakh** [comment]
ekta pull request patheachi ota merge kore neo

Ususal steps of collaborative development in github:
1. Open repository, merge any pending pull requests if you think they
   should be merged.
2. Open project folder, and do:

git pull github maser

here "github" is the remote name. it may be origin or whatever you named it.
1. If there are any merge conflicts then resolve and merge.
2. Work, and commit your changes and push.

**Comment by archie94** [comment]
@ghoshbishakh Writing the file manager with reference to your python script. Not clear on two things
1. what does  def checkChecksum(self, fileId) do?  
2. how to generate fileID for each file present?

**Comment by ghoshbishakh** [comment]
@archie94 actually that calculates the checksum of the file content and assigns it as fileID. Leave that part or hardcode something. Push whatever you have done till now.

**Comment by archie94** [comment]
@ghoshbishakh Pushed works up to today. I cannot work for the next two days. If you can you may modify whatever you feel like. Will resume from Saturday.

**Comment by ghoshbishakh** [comment]
@archie94 thanks! ill take a look tomorrow
