### ISSUE TITLE
Redundant downloads on resuming download of a file

### ISSUE THREAD

**Issue by archie94** [archie94/PSync#15]

**Comment by archie94** [comment]
@ghoshbishakh did u find any solution ?

**Comment by ghoshbishakh** [comment]
@archie94 I will stay at department from 3.30 today. Will try to find something then.

**Comment by archie94** [comment]
I have an exam so I will join you tomorrow

**Comment by ghoshbishakh** [comment]
@archie94 
i think i have spotted the issue.

I will make a PR after testing.
